# Generated by Django 4.2.4 on 2023-08-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='predictor_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='Date_of_Birth',
        ),
        migrations.AddField(
            model_name='user',
            name='User_Age',
            field=models.CharField(default='DEFAULT VALUE', max_length=2),
        ),
    ]
