# Generated by Django 4.2.4 on 2023-08-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_predictor_data_remove_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_Age',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
