# Generated by Django 4.2.4 on 2023-08-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_alter_user_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor_data',
            name='Polydipsia',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='predictor_data',
            name='Polyphagia',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='predictor_data',
            name='Polyuria',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='predictor_data',
            name='partial_paresis',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='predictor_data',
            name='sudden_weight_loss',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='predictor_data',
            name='weakness',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
