# Generated by Django 4.2.4 on 2023-08-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0009_delete_user_predictor_data_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor_data',
            name='Gender',
            field=models.PositiveBigIntegerField(choices=[(1, 'Male'), (2, 'Female')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='Obesity',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='Polydipsia',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='Polyphagia',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='Polyuria',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='User_Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='delayed_healing',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='partial_paresis',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='sudden_weight_loss',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='weakness',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=10, null=True),
        ),
    ]
