# Generated by Django 4.2.4 on 2023-08-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0013_alter_predictor_data_obesity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor_data',
            name='Obesity',
            field=models.PositiveBigIntegerField(choices=[(0, 'YES'), (1, 'NO')], null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='Polydipsia',
            field=models.PositiveBigIntegerField(choices=[(0, 'YES'), (1, 'NO')], null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='Polyphagia',
            field=models.PositiveBigIntegerField(choices=[(0, 'YES'), (1, 'NO')], null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='Polyuria',
            field=models.PositiveBigIntegerField(choices=[(0, 'YES'), (1, 'NO')], null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='delayed_healing',
            field=models.PositiveBigIntegerField(choices=[(0, 'YES'), (1, 'NO')], null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='partial_paresis',
            field=models.PositiveBigIntegerField(choices=[(0, 'YES'), (1, 'NO')], null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='predictions',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='sudden_weight_loss',
            field=models.PositiveBigIntegerField(choices=[(0, 'YES'), (1, 'NO')], null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='weakness',
            field=models.PositiveBigIntegerField(choices=[(0, 'YES'), (1, 'NO')], null=True),
        ),
    ]
