# Generated by Django 4.2.4 on 2023-08-26 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0014_alter_predictor_data_obesity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor_data',
            name='User_Age',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(80)]),
        ),
    ]
