# Generated by Django 4.2.4 on 2023-08-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0015_alter_predictor_data_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor_data',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
    ]
