# Generated by Django 4.2.4 on 2023-08-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0016_alter_predictor_data_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor_data',
            name='Irritability',
            field=models.PositiveBigIntegerField(choices=[(0, 'NO'), (1, 'YES')], null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('LGBTIQA+', ' LGBTIQA+')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='Obesity',
            field=models.PositiveBigIntegerField(choices=[(0, 'NO'), (1, 'YES')], null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='Polydipsia',
            field=models.PositiveBigIntegerField(choices=[(0, 'NO'), (1, 'YES')], null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='Polyphagia',
            field=models.PositiveBigIntegerField(choices=[(0, 'NO'), (1, 'YES')], null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='Polyuria',
            field=models.PositiveBigIntegerField(choices=[(0, 'NO'), (1, 'YES')], null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='delayed_healing',
            field=models.PositiveBigIntegerField(choices=[(0, 'NO'), (1, 'YES')], null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='partial_paresis',
            field=models.PositiveBigIntegerField(choices=[(0, 'NO'), (1, 'YES')], null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='sudden_weight_loss',
            field=models.PositiveBigIntegerField(choices=[(0, 'NO'), (1, 'YES')], null=True),
        ),
        migrations.AlterField(
            model_name='predictor_data',
            name='weakness',
            field=models.PositiveBigIntegerField(choices=[(0, 'NO'), (1, 'YES')], null=True),
        ),
    ]
